FROM python:3.9

RUN apt-get update -y
RUN apt-get install nano
RUN apt-get upgrade -y zlib1g subversion
RUN apt-get install -y openssl/stable-security ldap-utils/stable-security
RUN pip install pymongo wget fsspec xarray scipy geopy

WORKDIR /app
COPY . .
RUN chown -R 1000660000 /app
CMD python -u roundtrip.py